/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function startWebsocketServer(port: number, onConnect: (...args: any[]) => any): Promise<void>
export declare class WebSocketServer {
  constructor(callback: (err: null | Error, result: number) => void)
}
